name: BuildAndTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 5.0.x
        
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.x
        
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 2.1.x
        
    # .NET Frameworks are preinstalled
                
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
